[package]
name = "rgfw"
version = "0.1.0"
description = "Safe Rust bindings for RGFW."
readme = "../README.md"
keywords = ["bindings", "windowing", "crossplatform"]
edition = "2021"

[dependencies]
num-derive = "0.4.2"
num-traits = "0.2.19"
rgfw-sys = { path = "../rgfw-sys" }
